config/routes.rb
Rails.application.routes.draw do
#   get 'welcome/index'
#   For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

#   root 'welcome#index'
#   resources :articles do
#     resources :comments
#   end
Rails.application.routes.draw do
  resources :patients do
    collection do
      get :graph
    end
end
resources :users, only: [:new, :create, :index]
resources :patients


#   resources :users, except: [::destroy]
  get 'register', to: 'users#new'
  post 'register', to: 'users#create'
  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'
  post 'generate', to: 'patients#generate'
  delete 'clean', to: 'patients#clean'
  get 'dashboard', to: 'patients#dashboard'

  root 'patients#index'
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
    belongs_to :user
    
    validates :patient_name, presence: true, length: { minimum: 1 }
    scope :count_by_day, -> { group_by_day(:created_at).count }
    
    def self.search(term, per_page, current_page)
      patients = Patient.offset((current_page - 1) * per_page).limit(per_page)
      if term.present?
        # Use ILIKE for case-insensitive search in PostgreSQL
        patients = patients.where("category ILIKE ?", "%#{term}%")
      end
      patients
    end
  end
  

app/models/user.rb
class User < ApplicationRecord
    has_many :patients
    enum role: { receptionist: 1, doctor: 2, admin: 3}
    before_create :set_default_role

    private
  
    def set_default_role
      self.role ||= :doctor
    end
    after_initialize :set_default_role, if: :new_record?

    ROLES = %w[patient doctor receptionist]

    validates :role, presence: true, inclusion: { in: ROLES }
    before_save { self.email = email.downcase }

    validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }

    validates :password, presence: true, length: { minimum: 6, maximum: 30 }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :require_user

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            redirect_to login_path
        end
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
    skip_before_action :require_user, only: [:new, :create]

    def new
    end

    def create
        user = User.find_by(email: params[:email].downcase)
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            flash[:success] = "Your have successfully logged in."
            redirect_to patients_path
        else
            flash[:warning] = "Either your email or password is incorrect."
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "Your have successfully logged out."
        redirect_to patients_path
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  skip_before_action :require_user, only: [:index, :show,:clean]
  
    def index
      @per_page = 12
      @current_page = [params.fetch(:page, 1).to_i, 1].max
      @total_pages = (Patient.count.to_f / @per_page.to_f).ceil
      @patients = Patient.search(params[:term], @per_page, @current_page)
    end
    def graph
      @patient_counts = Patient.count_by_day
         render 'graph'
    end
    def show
      @patient = Patient.find(params[:id])
    end
  
    def new
      @patient = Patient.new
    end
  
    def edit
      redirect_not_same_user
      @patient = Patient.find(params[:id])
    end
  
    def create
      @current_user = current_user
      
      @patient = @current_user.patients.new(patient_params)
  
      if @patient.save
        redirect_to @patient
      else
        render 'new'
      end
    end
  
    def update
      redirect_not_same_user
      @patient = Patient.find(params[:id])
      if @patient.update(patient_params)
        redirect_to @patient
      else
        render 'edit'
      end
    end
  
    def destroy
      redirect_not_same_user
      @patient = Patient.find(params[:id])
      @patient.destroy
  
      redirect_to patients_path
    end
  
    def clean
      current_user.patients.destroy_all
      redirect_to patients_path, notice: "All patients cleaned successfully."
    end
    def dashboard
      @per_page = 12
      @current_page = [params.fetch(:page, 1).to_i, 1].max
      @total_pages = (Patient.where(user_id: current_user.id).count.to_f / @per_page.to_f).ceil
      @patients = Patient.offset((@current_page - 1) * @per_page).limit(@per_page).where(user_id: current_user.id)
      render :template => "patients/index.html.erb"
    end
  
    private
  
    def patient_params
      params.require(:patient).permit(:patient_name, :category, :description, :contact_email)
    end
    def authorize_doctor
      unless current_user&.role == 'doctor'
        flash[:alert] = "Only doctors can access this page."
        redirect_to root_path
      end
    end
    def redirect_not_same_user
      @patient = Patient.find(params[:id])
      redirect_to patients_path unless current_user.id == @patient.user.id
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_user, only: [:new, :create]

    def index
      @users = User.all
    end
  
    def new
      @user = User.new
    end
    def create
        @user = User.new(user_params)
          if @user.save
            redirect_to users_path, notice: 'User was successfully created.'
          else
            render :new
          end
      end

    private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation,:role)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def session_link
        if logged_in?
            link_to "Logout", logout_path, method: :delete, :class => "p-2 text-dark"
        else
            link_to "Login", login_path, :class => "p-2 text-dark"
        end
    end
end

app/helpers/doctors/patients_helper.rb
module Doctors::PatientsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
    <div class="container">
      <%= link_to "KD Hospital", root_path, class: 'navbar-brand brand-name' %>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <% if logged_in? %>
            <li class="nav-item">
              <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Add", new_patient_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Clean", clean_path, class: "nav-link", method: :delete, data: { confirm: "Are you sure?" } %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Register", register_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>

        <%= form_tag(patients_path, method: "get", class: "form-inline my-2 my-lg-0") do %>
          <div class="input-group">
            <%= text_field_tag(:term, params[:term], type: "search", placeholder: "Search by category...", class: "form-control") %>
            <div class="input-group-append">
              <%= submit_tag("Search", class: "btn btn-primary") %>
            </div>
          </div>
        <% end %>

        <%= session_link %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>KD Hospital</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag  "https://use.fontawesome.com/releases/v5.10.2/css/all.css" %>
    <%= stylesheet_link_tag  "https://use.fontawesome.com/releases/v5.10.2/css/v4-shims.css" %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartkick"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= render 'layouts/header' %>

  <% flash.each do |key, message| %>
    <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
        <%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
  <% end %>

  <%= yield %>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/views/logins/new.html.erb
<div class="row mt-5">
    <div class="col-md-6 m-auto">
        <div class="card card-body login-form" style="border-style: none">
            <h1 class="text-center mb-3"><i class="fas fa-sign-in-alt"></i>  Login</h1>

            <%= form_with url: login_path, local: true do |form| %>
                <div class="form-group">
                    <%= form.label :email, "Email" %><br>
                    <%= form.email_field :email, :class => 'form-control', placeholder: "Enter Email" %>
                </div>

                <div class="form-group">
                    <%= form.label :password, "Password" %><br>
                    <%= form.password_field :password, :class => 'form-control', placeholder: "Enter Password" %>
                </div>

                <%= form.submit "Login", :class => 'btn btn-primary btn-block' %>
            <% end %>

            <p class="lead mt-4">No Account? <%= link_to 'Register', register_path %></p>
        </div>
    </div>
</div>

app/views/patients/_form.html.erb
<%= form_with model: @patient, local: true do |form| %>
    <% if @patient.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h6>
          <%= pluralize(@patient.errors.count, "error") %> prohibited
          this patient from being saved:
        </h6>
        <ul>
          <% @patient.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :patient_name, "Patient Name" %><br>
      <%= form.text_field :patient_name, :class => 'form-control', placeholder: "Patient Name" %>
    </div>

    <div class="form-group">
      <%= form.label :category, "Illness" %><br>
      <%= form.text_field :category, :class => 'form-control', placeholder: "Category" %>
    </div>

    <div class="form-group">
      <%= form.label :description, "Description" %><br>
      <%= form.text_area :description, :class => 'form-control', :rows => 3 %>
    </div>
    <div class="form-group">
      <%= form.label :contact_email, "Email Address" %><br>
      <%= form.email_field :contact_email, :class => 'form-control', placeholder: @current_user.email %>
    </div>

    <% if @patient.id.present? %>
        <%= form.submit "Update", :class => 'btn btn-primary' %>
    <% else %>
        <%= form.submit "Submit", :class => 'btn btn-primary' %>
    <% end %>

    <% if @patient.id != nil && logged_in? %>
    <%= link_to 'Remove', patient_path(@patient), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    <% end %>
<% end %>

app/views/patients/edit.html.erb
<div class="container">
    <h1>Edit a patient</h1>
    <%= render 'form' %>
</div>

app/views/patients/graph.html.erb
<div class="container">
  <h1>Patients Registered by Day</h1>
  <canvas id="patientsChart" width="400" height="200"></canvas>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var ctx = document.getElementById('patientsChart').getContext('2d');
    new Chart(ctx, {
      type: 'line',
      data: {
        labels: <%= @patient_counts.keys.map { |date| date.strftime('%Y-%m-%d') }.to_json.html_safe %>,
        datasets: [{
          label: 'Patients Registered',
          data: <%= @patient_counts.values.to_json.html_safe %>,
          backgroundColor: 'rgba(54, 162, 235, 0.2)',
          borderColor: 'rgba(54, 162, 235, 1)',
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero: true
            }
          }]
        }
      }
    });
  });
</script>

app/views/patients/index.html.erb
<main role="main">
  <div class="album py-5 bg-light">
    <div class="container">

      <% if @patients.any?&&logged_in? %>
        <div class="row row-cols-1 row-cols-md-3">
          <% @patients.each do |patient| %>
            <div class="col mb-4">
              <div class="card h-100 shadow-sm">
                <div class="card-body">
                  <h5 class="card-title"><%= patient.patient_name %></h5>
                  <p class="card-text text-muted mb-3"><%= patient.description.truncate(80) %></p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <%= link_to 'View', patient_path(patient), class: "btn btn-sm btn-outline-primary" %>
                      <%= link_to 'Edit', edit_patient_path(patient), class: "btn btn-sm btn-outline-secondary" %>
                    </div>

                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>

        <nav aria-label="Patients Pagination">
          <ul class="pagination justify-content-center">
            <% if @current_page > 1 %>
              <li class="page-item">
                <%= link_to "First", patients_path(page: 1), class: "page-link" %>
              </li>
            <% end %>

            <% ([@current_page - 2, 1].max..[@current_page + 2, @total_pages].min).each do |i| %>
              <% if i == @current_page %>
                <li class="page-item active" aria-current="page">
                  <span class="page-link"><%= i %><span class="sr-only">(current)</span></span>
                </li>
              <% else %>
                <li class="page-item">
                  <%= link_to i, patients_path(page: i), class: "page-link" %>
                </li>
              <% end %>
            <% end %>

            <% if @current_page < @total_pages %>
              <li class="page-item">
                <%= link_to "Last", patients_path(page: @total_pages), class: "page-link" %>
              </li>
            <% end %>
          </ul>
        </nav>

      <% else %>
        <% if logged_in? %>
        <div class="row">
            <div class="col text-center">
            <p>No patients available</p>
            </div>
        </div>
        <% else %>
        <div class="row">
            <div class="col text-center">
            <p>Please Login to view patients</p>
            </div>
        </div>
        <% end %>
      <% end %>

    </div>
  </div>
</main>

app/views/patients/new.html.erb
<div class="container">
    <h1>Register a new patient</h1>
    <%= render 'form' %>
</div>

app/views/patients/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-body">
      <h3 class="card-title"><%= @patient.patient_name %></h3>
      <p class="card-text lead"><%= @patient.description %></p>
      
      <div class="row">
        <div class="col-md-6">
          <p class="card-text"><strong>Category:</strong> <%= @patient.category %></p>
        </div>
      </div>
      
      <% if logged_in? && current_user.id == @patient.user.id %>
        <div class="d-flex justify-content-between align-items-center mt-3">
          <div>
            <%= link_to 'Edit', edit_patient_path(@patient), class: "btn btn-warning me-2" %>
            <%= link_to 'Remove', patient_path(@patient), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </div>
          <div>
            <%= mail_to @patient.contact_email, "Contact #{@patient.user.name}",
                        class: "btn btn-primary buy-btn", subject: "Regarding patient: #{@patient.patient_name}" %>
          </div>
        </div>
      <% else %>
        <div class="mt-3">
          <%= mail_to @patient.contact_email, "Contact #{@patient.user.name}",
                      class: "btn btn-primary buy-btn btn-block", subject: "Regarding patient: #{@patient.patient_name}" %>
        </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row mt-5">
    <div class="col-md-6 m-auto">
        <div class="card card-body login-form" style="border-style: none">
            <h1 class="text-center mb-3"><i class="fas fa-user-plus"></i> Register</h1>

                <%= form_with scope: @user, url: register_path, local: true do |form| %>
                    <% if @user.errors.any? %>
                        <div id="error_explanation" class="alert alert-danger">
                            <h6>
                                <%= pluralize(@user.errors.count, "error") %> prohibited
                                this user from being created:
                            </h6>
                            <ul>
                                <% @user.errors.full_messages.each do |msg| %>
                                    <li><%= msg %></li>
                                <% end %>
                            </ul>
                        </div>
                    <% end %>

                    <div class="form-group">
                        <%= form.label :name, "Name" %><br>
                        <%= form.text_field :name, :class => 'form-control', placeholder: "Enter Name" %>
                    </div>

                    <div class="form-group">
                        <%= form.label :email, "Email" %><br>
                        <%= form.email_field :email, :class => 'form-control', placeholder: "Enter Email" %>
                    </div>

                    <div class="form-group">
                        <%= form.label :password, "Password" %><br>
                        <%= form.password_field :password, :class => 'form-control', placeholder: "Create Password" %>
                    </div>

                    <div class="form-group">
                        <%= form.label :password_confirmation, "Confirm Password" %><br>
                        <%= form.password_field :password_confirmation, :class => 'form-control', placeholder: "Confirm Password" %>
                    </div>
                    <div class="form-group">
                    <%= form.label :role %><br>
                    <%= form.select :role, options_for_select([["Doctor", "doctor"],["Receptionist","receptionist"]], selected: "patient"), {}, class: 'form-control' %>
                  </div>
                    <%= form.submit "Register", :class => 'btn btn-primary btn-block' %>
                <% end %>
        <p class="lead mt-4">Have an Account? <%= link_to 'Login', login_path %></p>
        </div>
    </div>
</div>